version: '3'

services:
  app-caching:
    container_name: stac-fastapi-caching
    image: stac-utils/stac-fastapi-caching
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - RELOAD=true
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
    ports:
      - "8081:8080"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
      # - ./esdata:/usr/share/elasticsearch/data
    depends_on:
      - tile38
    command:
      bash -c "./scripts/wait-for-it-es.sh tile38:9851 && python -m stac_fastapi.caching.app"

  tile38:
    image: "tile38/tile38"
    ports:
     - "9851:9851"
