name: stac-fastapi-caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - features/**

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:

      tile38_svc:
        image: "tile38/tile38"
        ports:
          - 9851:9851

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Lint code
        uses: pre-commit/action@v2.0.3

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install tile38 stac-fastapi
        run: |
          pip install ./stac_fastapi/caching[dev,server]

      - name: Run test suite against tile38
        run: |
          cd stac_fastapi/caching && pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing
          38_PORT: 9851
          38_HOST: 172.17.0.1